self_a:
  policy_config_path: random3/policy_config/rnn_policy_config.pkl
  featurize_type: ppo
  train: False
  model_path:
    actor: random3/cole/s2/cole-S2-s50/1.pt

self_b:
  policy_config_path: random3/policy_config/rnn_policy_config.pkl
  featurize_type: ppo
  train: False
  model_path:
    actor: random3/cole/s2/cole-S2-s50/1.pt
